- name: modify nginx_config
  template: 
    src=nginx.conf.j2 
    dest={{ nginx_conf }}
  notify: restart service

- name: modify nginx_default_config
  template:
    src=default.conf.j2 
    dest={{ default_conf }}
  notify: restart service

- name: cp data
  template:
    src=index.html.j2
    dest={{ www }}/index.html
  notify: restart service

